name: conda-root-env
channels:
  - conda-forge 
dependencies:
  - python>=3.6
  - root
  - uproot
  - scipy
  - matplotlib
  - mesa-libGL
  - mesa-dri-drivers
  - libselinux
  - libXdamage
  - libXxf86vm
  # Required for ROOT's tests as they use lsb_release
  - redhat-lsb-core
